auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h   # Update to 24h for boltdb-shipper

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false  # Disable structured metadata

compactor:
  working_directory: /loki/compactor  # Set working directory for compactor

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
