server:
  http_listen_port: 9080  # Port Promtail will listen on
  grpc_listen_port: 0     # Disable gRPC server

positions:
  filename: /tmp/positions.yaml  # File to track the last read positions of logs

clients:
  - url: http://172.17.0.5:3100/loki/api/v1/push  # Loki's HTTP API endpoint

scrape_configs:
  - job_name: log-files
    static_configs:
      - targets:
          - localhost
        labels:
          job: "logs"
          host: "localhost"
          __path__: "/var/log/app.log"


