server:
  http_listen_port: 9080
  grpc_listen_port: 42041

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.17.0.5:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'inventory-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: inventory-logs
          __path__: "/var/log/app.log"
